In [16]:
%matplotlib inline
from sklearn.svm import SVC
from sklearn.datasets import load_svmlight_file
from sklearn.cross_validation import cross_val_score
from hyppo import BayesOptCV
import matplotlib.pyplot as sns

In [10]:
def get_data(fpath):
    data = load_svmlight_file(fpath)
    return data[0], data[1]

train_path = 'splice_data/splice_noise_train.txt'
test_path = 'splice_data/splice_noise_test.txt'

train_data, train_labels = get_data(train_path)
test_data, test_label = get_data(test_path)

from sklearn.preprocessing import MinMaxScaler

In [11]:
scaler = MinMaxScaler(feature_range=(-1, 1))

train_data = scaler.fit_transform(train_data.toarray())
test_data = scaler.transform(test_data.toarray())

print train_data.shape
print test_data.shape
import numpy as np
f = lambda x: np.sin(x)
sigma = 0.02  # noise variance.


(2375, 60)
(800, 60)


In [17]:
def sin(C):
    
    return f(C) + sigma * np.random.randn(1)[0]
def svccv(C, gamma):
    return 1 - cross_val_score(SVC(C=C, kernel='rbf', gamma=gamma , random_state=2),
                           train_data, train_labels, 'f1', cv=5).mean()
                           
svcBO = BayesOptCV(svccv, param_grid={'C':{'type':'float', 'min':6.4e-05, 'max':60},
                                      'gamma':{'type':'float', 'min':6.4e-5, 'max':10}},
                   bigger_is_better=False, verbose=2)

svcBO.initialize(num_init=10, init_grid={'C': [1, 15, 60], 'gamma':[1, 5, 10]})
# kernel_param = {'nugget':0.0000001}
kernel_param = {'theta0':0.1}
acqui_param = {'kappa':4} 
svcBO.optimize(kernel_param=kernel_param, acqui_param=acqui_param, n_iter=10, acqui_type='ucb', n_acqui_iter=200)
print('Final Results')                             
print('SVC: %f' % svcBO.report['best']['best_val'])
#plt.show()

[[ 1  1]
 [15  5]
 [60 10]]
[ 0.30205296  0.30753833  0.30899542]
Best x at round 0 is: [  6.00000000e+01   6.40000000e-05]
Best y at round 0 is: 0.324965132497
best so far 0.30205296378
params{'C': 1.0, 'gamma': 1.0}
Best x at round 1 is: [ 25.45864955  10.        ]
Best y at round 1 is: 0.324965132497
best so far 0.241374041224
params{'C': 60.0, 'gamma': 6.4000000000064006e-05}
Best x at round 2 is: [  6.40000000e-05   6.56981784e+00]
Best y at round 2 is: 0.324965132497
best so far 0.241374041224
params{'C': 60.0, 'gamma': 6.4000000000064006e-05}
Best x at round 3 is: [  6.40000000e-05   8.37025253e+00]
Best y at round 3 is: 0.324965132497
best so far 0.241374041224
params{'C': 60.0, 'gamma': 6.4000000000064006e-05}
Best x at round 4 is: [  6.40000000e-05   7.34208096e+00]
Best y at round 4 is: 0.324965132497
best so far 0.241374041224
params{'C': 60.0, 'gamma': 6.4000000000064006e-05}
Best x at round 5 is: [ 60.          6.1264888]
Best y at round 5 is: 0.324965132497
best so far 0

In [19]:

def svccv(C):
    return 1 - cross_val_score(SVC(C=C, kernel='rbf', gamma=3, random_state=2),
                           train_data, train_labels, 'f1', cv=5).mean()
                           
svcBO = BayesOptCV(svccv, param_grid={'C':{'type':'float', 'min':6.4e-05, 'max':60}},
                   bigger_is_better=False, verbose=2)

svcBO.initialize(num_init=10, init_grid={'C': [1, 15, 60]})
# kernel_param = {'nugget':0.0000001}
kernel_param = {'theta0':0.1}
acqui_param = {'kappa':4} 
svcBO.optimize(kernel_param=kernel_param, acqui_param=acqui_param, n_iter=10, acqui_type='ucb', n_acqui_iter=200)
print('Final Results')                             
print('SVC: %f' % svcBO.report['best']['best_val'])
#plt.show()

[[ 1]
 [15]
 [60]]
[ 0.30753833  0.3058715   0.3058715 ]
Best x at round 0 is: [ 43.79013592]
Best y at round 0 is: 0.324965132497
best so far 0.305871503402
params{'C': 15.0}
Best x at round 1 is: [ 30.28178677]
Best y at round 1 is: 0.324965132497
best so far 0.305871503402
params{'C': 15.0}
Best x at round 2 is: [ 54.3048112]
Best y at round 2 is: 0.324965132497
best so far 0.305871503402
params{'C': 15.0}
Best x at round 3 is: [  6.40000000e-05]
Best y at round 3 is: 0.324965132497
best so far 0.305871503402
params{'C': 15.0}
Best x at round 4 is: [ 0.0201379]
Best y at round 4 is: 0.324965132497
best so far 0.305871503402
params{'C': 15.0}


Exception: Multiple input features cannot have the same target value.